### ISSUE TITLE
Real issue

### ISSUE THREAD

**Issue by Emeradonis** [Emeradonis/Feedies#1]
How can i update the changes to the repository?? Halear

**Comment by Emeradonis** [comment]
git pull origin main

**Comment by fadouaabdoul** [comment]
open it and close by yourself woow haha

**Comment by Emeradonis** [comment]
> open it and close by yourself woow haha

iwa la 7ayata liman tonadi laoma ndiro progress hna

**Comment by fadouaabdoul** [comment]
progress vu.
