### ISSUE TITLE
Fix sign in with google

### ISSUE THREAD

**Issue by Emeradonis** [Emeradonis/Feedies#15]
there is SHA fingerprint that should be activated that i could complete. you can refer back to the vid 5 of the series you sent me he talked about it in min 3:04

**Comment by fadouaabdoul** [comment]
I need more explanation about this matter. While also posting the link to the vid for reference :)

**Comment by Emeradonis** [comment]
Sure, as i told you before it doesnot gimme the same thing that it gives him in the video, soo i could not find a function that s apparently very important for the sign in (with google) to work. it is called SHA fingerprint something. it should be activated.
this is the link to the video: https://www.youtube.com/watch?v=zvZleTXypd0

**Comment by fadouaabdoul** [comment]
Understanding why you can't find that view, you are using the web app in firebase not the android app , SHA fingerprint is not available in the web part.
You can skip that part as you don't need it for the moment.
